# Generated by Django 3.0.8 on 2020-07-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200723_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
