# Generated by Django 3.0.8 on 2020-07-23 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20200723_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
